### ISSUE TITLE
Make lodash dependency more granular

### ISSUE THREAD

**Issue by richard-viney** [viruschidai/diff-json#11]
Hi,

The dependency on `lodash` increases the bundle size of consuming applications. Could we switch to the packages for the individual `lodash` functions to `lodash.intersection`, `lodash.difference` etc.?

The update process is fairly trivial, would be happy to do a PR for it.

Thanks.

**Comment by thebillg** [comment]
thanks, @richard-viney a PR would be great

**Comment by richard-viney** [comment]
PR submitted: #12

**Comment by richard-viney** [comment]
If you had a moment to review & merge #12 and then do a release that would be greatly appreciated :+1:.
