### ISSUE TITLE
Array item order matters, however When object in an Array change order, no diff is generated

### ISSUE THREAD

**Issue by dhwang** [viruschidai/diff-json#18]
Need to be able to show that two items in an array switched order for example

{ a  : [ { id: b, value: 1}, {id: a, value: 2}] }

{ a  : [ { id: a, value: 2}, {id: b, value: 1}] }

should show a difference as order matters in an array

**Comment by nahtnam** [comment]
Looks like it works:

```
var changesets = require('diff-json');

console.log(changesets.diff(
  { a : [ { id: 'b', value: 1}, {id: 'a', value: 2}] },
  { a : [ { id: 'a', value: 2}, {id: 'b', value: 1}] }));
```

returns

```
```

**Comment by viruschidai** [comment]
yes, it should work by default
