### ISSUE TITLE
lodash dependency in the npm package

### ISSUE THREAD

**Issue by gavinaiken** [viruschidai/diff-json#9]
Hi, could you possibly publish an updated version of `diff-json` to npm? The dependency on lodash was updated here: https://github.com/viruschidai/diff-json/commit/7a1ac6a2f6cf1e254fcb24eac48687d7b96140e0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 but that doesn't seem to be included in the most recent version on npm. Would be great to get a new version on npm with that updated lodash dependency.

**Comment by viruschidai** [comment]
sure

**Comment by viruschidai** [comment]
Done released 1.1.0
